In [1]:
import pandas as pd
# Upload file
from google.colab import files
uploaded = files.upload()
# Read Txt file
df = pd.read_csv("unclean_crm_dataset.txt", delimiter="|")
# Convert to CSV
df.to_csv("Clean_Crm_Dataset.csv", index=False)

Saving unclean_crm_dataset.txt to unclean_crm_dataset.txt

In [2]:
# Download CSV file
files.download("Clean_Crm_Dataset.csv")

In [3]:
# Load the dataset
from google.colab import files
uploaded = files.upload()
# Function to load CSV file using Pandas
import pandas as pd
dataset = pd.read_csv('Clean_Crm_Dataset.csv')
dataset.head()

Saving Clean_Crm_Dataset.csv to Clean_Crm_Dataset (1).csv

,lead_id,lead_name,email,phone,lead_source,industry,country,state,city,deal_value,deal_stage,assigned_to,created_date,last_contacted,notes
0,L743047,Neha,NaN,NaN,Website,NaN,India,NaN,New York,NaN,Qualified,Anita,2023/12/10,01-06-2024,Interested
1,L919250,Riya,NaN,9876543210,Website,Finance,NaN,CA,Mumbai,96479.0,Closed Lost,NaN,2023/12/10,NaN,NaN
2,L233529,Priya,invalid_email,NaN,Referral,Retail,NaN,CA,Dubai,NaN,NaN,Meera,NaN,NaN,NaN
3,L243465,Priya,invalid_email,NaN,NaN,Healthcare,USA,CA,Dubai,NaN,NaN,NaN,2023/12/10,NaN,Interested
4,L902054,Priya,test@gmail.com,+91-9988776655,NaN,Edu,NaN,NaN,Berlin,256272.0,NaN,NaN,2023/12/10,NaN,Not reachable

In [4]:
# Data Preprocessing
# Read CSV file
df = pd.read_csv("Clean_Crm_Dataset.csv")

# Convert column names to CAPITAL
df.columns = [col.upper() for col in df.columns]
print(df.columns)

Index(['LEAD_ID', 'LEAD_NAME', 'EMAIL', 'PHONE', 'LEAD_SOURCE', 'INDUSTRY',
       'COUNTRY', 'STATE', 'CITY', 'DEAL_VALUE', 'DEAL_STAGE', 'ASSIGNED_TO',
       'CREATED_DATE', 'LAST_CONTACTED', 'NOTES'],
      dtype='object')

In [5]:
# Remove Duplicate Records
df = df.drop_duplicates()

# String Cleaning
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

# Standardize Text Data
df["STATE"] = df["STATE"].str.upper()
df["COUNTRY"] = df["COUNTRY"].str.upper()

# CREATED_DATE → YYYY/MM/DD
df["CREATED_DATE"] = pd.to_datetime(
    df["CREATED_DATE"], errors="coerce"
).dt.strftime("%d-%m-%Y")

# LAST_CONTACTED → DD-MM-YYYY
df["LAST_CONTACTED"] = pd.to_datetime(
    df["LAST_CONTACTED"], dayfirst=True, errors="coerce"
).dt.strftime("%d-%m-%Y")

# Fill missing values with "NA"
df = df.fillna("NA")
df

,LEAD_ID,LEAD_NAME,EMAIL,PHONE,LEAD_SOURCE,INDUSTRY,COUNTRY,STATE,CITY,DEAL_VALUE,DEAL_STAGE,ASSIGNED_TO,CREATED_DATE,LAST_CONTACTED,NOTES
0,L743047,Neha,NA,NA,Website,NA,INDIA,NA,New York,NA,Qualified,Anita,10-12-2023,01-06-2024,Interested
1,L919250,Riya,NA,9876543210,Website,Finance,NA,CA,Mumbai,96479.0,Closed Lost,NA,10-12-2023,NA,NA
2,L233529,Priya,invalid_email,NA,Referral,Retail,NA,CA,Dubai,NA,NA,Meera,NA,NA,NA
3,L243465,Priya,invalid_email,NA,NA,Healthcare,USA,CA,Dubai,NA,NA,NA,10-12-2023,NA,Interested
4,L902054,Priya,test@gmail.com,+91-9988776655,NA,Edu,NA,NA,Berlin,256272.0,NA,NA,10-12-2023,NA,Not reachable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,L379007,Neha,test@gmail.com,NA,Cold Call,IT,INDIA,CA,Pune,NA,Qualified,Anita,10-12-2023,NA,NA
99996,L620141,Riya,test@gmail.com,+91-9988776655,Website,IT,GERMANY,BERLIN,Berlin,NA,NA,Anita,10-12-2023,01-06-2024,Follow up
99997,L145431,Mohd,invalid_email,NA,LinkedIn,IT,GERMANY,LONDON,Pune,NA,Closed Lost,Karan,NA,NA,NA
99998,L794877,John,NA,12345,Cold Call,IT,USA,CA,Dubai,NA,Prospect,Anita,NA,01-06-2024,NA
99999,L960212,Amit,NA,9876543210,NA,Edu,NA,TEXAS,New York,NA,Prospect,Meera,NA,NA,NA

In [6]:
# Save preprocessed file
df.to_csv("Preprocessed_CRM_Dataset.csv", index=False)
# Download preprocessed file
files.download("Preprocessed_CRM_Dataset.csv")